# Generated by Django 2.1.3 on 2018-11-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=8)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
