# Generated by Django 2.1.3 on 2018-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20181108_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
