# Generated by Django 2.1.3 on 2018-11-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='foods.SignUp'),
            preserve_default=False,
        ),
    ]
